### PR TITLE
Update solidusio references

### PR DESCRIPTION
**Pull request by DanielePalombo**
## Summary

We think that would be better to move this repo under solidusio

## Checklist

Check out our [PR guidelines](https://github.com/solidusio/.github/blob/master/CONTRIBUTING.md#pull-request-guidelines) for more details.

The following are mandatory for all PRs:

- [ ] I have written a thorough PR description.
- [ ] I have kept my commits small and atomic.
- [ ] [I have used clear, explanatory commit messages](https://github.com/solidusio/.github/blob/main/CONTRIBUTING.md#writing-good-commit-messages).

The following are not always needed:

- 📖 I have updated the README to account for my changes.
- 📑 I have documented new code [with YARD](https://www.rubydoc.info/gems/yard/file/docs/Tags.md).
- 🛣️ I have opened a PR to update the [guides](https://github.com/solidusio/edgeguides).
- ✅ I have added automated tests to cover my changes.
- 📸 I have attached screenshots to demo visual changes.

### CODE REVIEW

**Review by MassimilianoLattanzio — CHANGES_REQUESTED** [review]
There are some other `nebulab` references remaining:
- https://github.com/solidusio/rubocop-solidus/blob/a0c1f7d9c745cbe888f00f7d8ba474e814ac5bf8/CHANGELOG.md?plain=1#L7
- https://github.com/solidusio/rubocop-solidus/blob/a0c1f7d9c745cbe888f00f7d8ba474e814ac5bf8/relnotes/v0.1.2.md?plain=1#L3
- https://github.com/solidusio/rubocop-solidus/blob/a0c1f7d9c745cbe888f00f7d8ba474e814ac5bf8/changelog/fix_typos_in_readme_and_add_instructions.md?plain=1#L1

Additionally, checks are not passing, and I don't know why 🤷🏼

**Comment by DanielePalombo** [comment]
I have fixed the checks

**Comment by DanielePalombo** [comment]
> There are some other `nebulab` references remaining:
> 
> * https://github.com/solidusio/rubocop-solidus/blob/a0c1f7d9c745cbe888f00f7d8ba474e814ac5bf8/CHANGELOG.md?plain=1#L7
> * https://github.com/solidusio/rubocop-solidus/blob/a0c1f7d9c745cbe888f00f7d8ba474e814ac5bf8/relnotes/v0.1.2.md?plain=1#L3
> * https://github.com/solidusio/rubocop-solidus/blob/a0c1f7d9c745cbe888f00f7d8ba474e814ac5bf8/changelog/fix_typos_in_readme_and_add_instructions.md?plain=1#L1
> 
> Additionally, checks are not passing, and I don't know why 🤷🏼

@MassimilianoLattanzio these are references on changelog or release notes, I think we should keep them for historical data.
About the checks I have fixed them, FYI the problem was related to the fact that I have committed the *.gem files

**Comment by MassimilianoLattanzio** [comment]
> @MassimilianoLattanzio these are references on changelog or release notes, I think we should keep them for historical data.

Since the old link will be redirected to the new one, and the new link contains the same thing, why not move these links too? Anyway, it's not crucial, so you can skip them.

**Review by MassimilianoLattanzio — APPROVED** [review]

**Pull request merged**
